### ISSUE TITLE
No userdata/settings.json file

### ISSUE THREAD

**Issue by DavidMoritz** [mgierw/auto-foe#1]
Could you please provide an example json file?

**Comment by mgierw** [comment]
Added:
https://github.com/mgierw/auto-foe/commit/8294a07159b6b3e1fbd3040486d4661c952a1491

**Comment by DavidMoritz** [comment]
Thank you for adding the file. But there still aren't any options set for this user. The code looks as though the user can supply options as to which buildings get set, whether or not to do treasure hunt, etc. Am I mistaken in this? If not, then please show what some example options look like.

Thanks!

**Comment by mgierw** [comment]
Actually there is no option to set. All tasks should execute automatically without any configuration. The "web console" is provided only to see the status of most of the elements of the game. There is only one switch - pause.
