### ISSUE TITLE
needs some instructions on how to set some personnel preferences 

### ISSUE THREAD

**Issue by ophott** [mgierw/auto-foe#11]
Hi.. Great work...better than any foe bot which i came across....
I totally depend on Terrace farms for supplies.. but default setting for production is 5 minutes(Coins) in the bot.. So as i understood from code in cityproduction.jason file that i need to specify my preferences in .vscode/settings.json file. But i don't know how do i put 15 minute production in the file. Need some guidance for that..

Sorry for bad English..

**Comment by nguoingoai** [comment]
I think  this function feature will be add soon , I have review the source code and I think you can do it by yourself by changing some line in server/GreateBuildingsService.js
Just focus on 
![screen shot 2017-07-09 at 8 27 27 am](https://user-images.githubusercontent.com/28948005/27990418-a774751e-6480-11e7-9eff-100cb0b466ef.png)

"shortestTimeProductionWithoutRequirements.production_option || 0)"  here change it to specific number of your product you want to build, ex: 1 for 5 miniute , 2 for 15 minute ....

If you want only  Terrace farms to build 15 minute try to use if statement with buildingDefinition.name === "Terrace Farm"

Hope it work for you =))
