### ISSUE TITLE
New ERROR about the CityProductionService

### ISSUE THREAD

**Issue by nguoingoai** [mgierw/auto-foe#13]
Today new error come 

TypeError: Cannot read property 'available_products' of undefined
    at _.filter.map.b (/auto/server/CityProductionService.js:45:72)
    at arrayMap (auto/node_modules/lodash/lodash.js:660:23)
    at Function.map (auto/node_modules/lodash/lodash.js:9571:14)
    at interceptor (auto/node_modules/lodash/lodash.js:16970:35)
    at thru (auto/node_modules/lodash/lodash.js:8812:14)
    at auto/node_modules/lodash/lodash.js:4379:28
    at arrayReduce (auto/node_modules/lodash/lodash.js:704:21)
    at baseWrapperValue (auto(/root/Downloads/project1/node_modules/lodash/lodash.js:1880:16)
    at baseWrapperValue (auto/node_modules/lodash/lodash.js:4376:25)
^C

**Comment by DavidMoritz** [comment]
Yeah, I just started experiencing this error this morning. I'm not sure what would have changed, except maybe an update to the FOE servers.

@mgierw do you have any ideas?

**Comment by ophott** [comment]
working fine now....

**Comment by DavidMoritz** [comment]
@ophott were you experiencing the error before? If so, did you do anything to fix it?

**Comment by ophott** [comment]
oh no i'm still getting it... it comes at later stage... and bot was doing some other works..when i looked..

**Comment by DavidMoritz** [comment]
@ophott does everything else still operate correctly while this error is happening?

**Comment by DanAtkinson** [comment]
I've seen this error. It appears to happen when a production has finished. If I manually go in and assign productions, then go back and restart the service, it continues working until the productions have finished again. At which point, it collects them and then falls over once more.

**Comment by ophott** [comment]
so it's not able to set production.. i think innogames changed something..

**Comment by DavidMoritz** [comment]
It's important to note that his error came independent of any code changes to several users. Inno changing something is the likely cause.

**Comment by ophott** [comment]
can we skip this step where 'available_products' retrieve its value..?
i mean keep running other services...

**Comment by DavidMoritz** [comment]
perhaps. See if you can skip it. But it would seem to me that it would be an essential step to setting a production.

**Comment by ophott** [comment]
but if its not working than skipping it would be the best option for now..

**Comment by DavidMoritz** [comment]
well, the errors are annoying, but as far as I can tell, the other functions are still working, except for treasureService.

**Comment by mgierw** [comment]
The problem seems to be located at the previous line of code:
`var buildingDefinition = definitionService.findBuildingDefinition(b.cityentity_id);`
Try to dump value of `b` and `b.cityentity`.

There should be a check for undefined/null value of `buildingDefinition` and conditional execution of rest of code below.

**Comment by DavidMoritz** [comment]
@mgierw that seems good. Can you push those code changes?

**Comment by mgierw** [comment]
The problem is deeper - server doesn't send building definitions.
StartupService.js, line 24 - `getData.city_map.city_entities` is now empty array, and this is the root of the problem.

**Comment by mgierw** [comment]
Commited some changes.
Please check them out.

**Comment by ophott** [comment]
Seems to be working..

**Comment by nguoingoai** [comment]
Working fine , thanks guys so much !
