### ISSUE TITLE
Tradeding service not work 

### ISSUE THREAD

**Issue by nguoingoai** [mgierw/auto-foe#14]
Current in my inentory 
![screen shot 2017-07-20 at 6 42 12 pm](https://user-images.githubusercontent.com/28948005/28415775-5b3a9ddc-6d7b-11e7-9c15-98e145ac7c01.png)
No trade create , so is the trade  function work  correct !!!

**Comment by mgierw** [comment]
Trade offers are created to balance the amount of goods from the same era. Additionally there are selled the "green" goods only.

**Comment by nguoingoai** [comment]
Ok I see, let me monitor and report later if there is something wrong  , thanks you very much. By the way how about the automation build military , this function will  help me very much to Expedition war  . Is there any plan about it ? . Or just show me the createServerRequest format , I will do it by myself :)
