### ISSUE TITLE
Trading not work !!!

### ISSUE THREAD

**Issue by nguoingoai** [mgierw/auto-foe#17]
![screen shot 2017-07-29 at 11 29 03 pm](https://user-images.githubusercontent.com/28948005/28746404-dd7d3368-74b5-11e7-848d-3dc5c116e7f5.png)
I have stone  repository , but no trade created .

**Comment by mgierw** [comment]
Now should work: 100c41843d57baa6844bc2e4b5afecccde6ad0c3.

**Comment by nguoingoai** [comment]
Working now , Thanks you so much

**Comment by ophott** [comment]
Thanku..
